### ISSUE TITLE
Optional dependency on `clippy`

### ISSUE THREAD

**Issue by qinsoon** [marchelzo/doubly#1]
`clippy` requires nightly rust to compile, which makes `doubly` requires nightly rust. Consider using an optional dependency for `clippy` (the code below), as suggested in [https://pascalhertleif.de/artikel/good-practices-for-writing-rust-libraries/](url)
```
[dependencies]
clippy = {version = "0.0.21", optional = true}

[features]
default = []
dev = ["clippy"]
```

**Comment by marchelzo** [comment]
hey, thanks for the heads up. i've just removed clippy as a dependency altogether.
